<!DOCTYPE testSuite [
<!ELEMENT testSuite (dataCategory)+>
<!ATTLIST testSuite xmlns CDATA #FIXED "http://example.com/myns">
<!ELEMENT dataCategory (inputfile+)>
<!ATTLIST dataCategory name CDATA #REQUIRED
identifier NMTOKEN #REQUIRED>
<!ELEMENT inputfile (description, expectedOutput, outputImplementors*)>
<!ATTLIST inputfile location CDATA #REQUIRED
conformance-class (xml-global|xml-local|html-global|html-local) #REQUIRED>
<!ELEMENT description (#PCDATA)>
<!ATTLIST description assertions NMTOKENS #REQUIRED>
<!ELEMENT expectedOutput EMPTY>
<!ATTLIST expectedOutput location CDATA #REQUIRED>
<!ELEMENT outputImplementors EMPTY>
<!ATTLIST outputImplementors implementer (adobe|cocomore|dcu|enlaso|jsi|linguaserve|logrus|lucysoftware|moravia|shaun|tcd|tilde|ul|vistatec) #REQUIRED
location CDATA #REQUIRED>
]>
<testSuite xmlns="http://example.com/myns">

   <!--Translate-->   
   <dataCategory identifier="translate" name="Translate">
      <inputfile location="inputdata/translate/xml/translate1xml.xml" conformance-class="xml-global">
         <description assertions="translate-global">Global - Embedded rule</description>
         <expectedOutput location="expected/translate/xml/translate1xmloutput.txt"/>
         <outputImplementors implementer="enlaso" location="outputimplementors/enlaso/translate/xml/translate1xmloutput.txt"/>
         <outputImplementors implementer="ul" location="outputimplementors/ul/translate/xml/translate1xmloutput.txt"/>
         <outputImplementors implementer="shaun" location="outputimplementors/shaun/translate/xml/translate1xmloutput.txt"/>
         <outputImplementors implementer="dcu" location="outputimplementors/dcu/translate/xml/translate1xmloutput.txt"/>
         <outputImplementors implementer="linguaserve" location="outputimplementors/linguaserve/translate/xml/translate1xmloutput.txt"/>
         <outputImplementors implementer="adobe" location="outputimplementors/adobe/translate/xml/translate1xmloutput.txt"/>
      </inputfile>
      <inputfile location="inputdata/translate/html/translate7html.html" conformance-class="xml-global">
         <description assertions="translate-global its-param html5-global-rules">Global - Embedded rules &lt;its:param&gt;</description>
         <expectedOutput location="expected/translate/html/translate7htmloutput.txt"/>
         <outputImplementors implementer="enlaso" location="outputimplementors/enlaso/translate/html/translate7htmloutput.txt"/>
         <outputImplementors implementer="ul" location="outputimplementors/ul/translate/html/translate7htmloutput.txt"/>
         <outputImplementors implementer="shaun" location="outputimplementors/shaun/translate/html/translate7htmloutput.txt"/>
         <outputImplementors implementer="dcu" location="outputimplementors/dcu/translate/html/translate7htmloutput.txt"/>
         <outputImplementors implementer="cocomore" location="outputimplementors/cocomore/translate/html/translate7htmloutput.txt"/>
         <outputImplementors implementer="linguaserve" location="outputimplementors/linguaserve/translate/html/translate7htmloutput.txt"/>
         <outputImplementors implementer="lucysoftware" location="outputimplementors/lucysoftware/translate/html/translate7htmloutput.txt"/>
      </inputfile>
      <inputfile location="inputdata/translate/xml/translate9xml.xml" conformance-class="xml-global">
         <description assertions="translate-global its-param">Global - Embedded rules &lt;its:param&gt;</description>
         <expectedOutput location="expected/translate/xml/translate9xmloutput.txt"/>
         <outputImplementors implementer="enlaso" location="outputimplementors/enlaso/translate/xml/translate9xmloutput.txt"/>
         <outputImplementors implementer="ul" location="outputimplementors/ul/translate/xml/translate9xmloutput.txt"/>
         <outputImplementors implementer="shaun" location="outputimplementors/shaun/translate/xml/translate9xmloutput.txt"/>
         <outputImplementors implementer="dcu" location="outputimplementors/dcu/translate/xml/translate9xmloutput.txt"/>
         <outputImplementors implementer="linguaserve" location="outputimplementors/linguaserve/translate/xml/translate9xmloutput.txt"/>
         <outputImplementors implementer="adobe" location="outputimplementors/adobe/translate/xml/translate9xmloutput.txt"/>
      </inputfile>
      <inputfile location="inputdata/translate/xml/translate2xml.xml" conformance-class="xml-global">
         <description assertions="translate-global link-external-rules">Global - Linked rules</description>
         <expectedOutput location="expected/translate/xml/translate2xmloutput.txt"/>
         <outputImplementors implementer="enlaso" location="outputimplementors/enlaso/translate/xml/translate2xmloutput.txt"/>
         <outputImplementors implementer="ul" location="outputimplementors/ul/translate/xml/translate2xmloutput.txt"/>
         <outputImplementors implementer="shaun" location="outputimplementors/shaun/translate/xml/translate2xmloutput.txt"/>
         <outputImplementors implementer="dcu" location="outputimplementors/dcu/translate/xml/translate2xmloutput.txt"/>
         <outputImplementors implementer="linguaserve" location="outputimplementors/linguaserve/translate/xml/translate2xmloutput.txt"/>
         <outputImplementors implementer="adobe" location="outputimplementors/adobe/translate/xml/translate2xmloutput.txt"/>
      </inputfile>
      <inputfile location="inputdata/translate/xml/translate10xml.xml" conformance-class="xml-global">
         <description assertions="translate-global link-external-rules its-param">Global - Linked rules&lt;its:param&gt;</description>
         <expectedOutput location="expected/translate/xml/translate10xmloutput.txt"/>
         <outputImplementors implementer="enlaso" location="outputimplementors/enlaso/translate/xml/translate10xmloutput.txt"/>
         <outputImplementors implementer="ul" location="outputimplementors/ul/translate/xml/translate10xmloutput.txt"/>
         <outputImplementors implementer="shaun" location="outputimplementors/shaun/translate/xml/translate10xmloutput.txt"/>
         <outputImplementors implementer="dcu" location="outputimplementors/dcu/translate/xml/translate10xmloutput.txt"/>
         <outputImplementors implementer="linguaserve" location="outputimplementors/linguaserve/translate/xml/translate10xmloutput.txt"/>
         <outputImplementors implementer="adobe" location="outputimplementors/adobe/translate/xml/translate10xmloutput.txt"/>
      </inputfile>
      <inputfile location="inputdata/translate/html/translate1html.html" conformance-class="xml-global">
         <description assertions="translate-global html5-external-global-rules">Global - Linked rules</description>
         <expectedOutput location="expected/translate/html/translate1htmloutput.txt"/>
         <outputImplementors implementer="enlaso" location="outputimplementors/enlaso/translate/html/translate1htmloutput.txt"/>
         <outputImplementors implementer="ul" location="outputimplementors/ul/translate/html/translate1htmloutput.txt"/>
         <outputImplementors implementer="shaun" location="outputimplementors/shaun/translate/html/translate1htmloutput.txt"/>
         <outputImplementors implementer="dcu" location="outputimplementors/dcu/translate/html/translate1htmloutput.txt"/>
         <outputImplementors implementer="cocomore" location="outputimplementors/cocomore/translate/html/translate1htmloutput.txt"/>
         <outputImplementors implementer="linguaserve" location="outputimplementors/linguaserve/translate/html/translate1htmloutput.txt"/>
         <outputImplementors implementer="lucysoftware" location="outputimplementors/lucysoftware/translate/html/translate1htmloutput.txt"/>
      </inputfile>
      <inputfile location="inputdata/translate/html/translate6html.html" conformance-class="xml-global">
         <description assertions="translate-global html5-external-global-rules its-param">Global - Linked rules &lt;its:param&gt;</description>
         <expectedOutput location="expected/translate/html/translate6htmloutput.txt"/>
         <outputImplementors implementer="enlaso" location="outputimplementors/enlaso/translate/html/translate6htmloutput.txt"/>
         <outputImplementors implementer="ul" location="outputimplementors/ul/translate/html/translate6htmloutput.txt"/>
         <outputImplementors implementer="shaun" location="outputimplementors/shaun/translate/html/translate6htmloutput.txt"/>
         <outputImplementors implementer="dcu" location="outputimplementors/dcu/translate/html/translate6htmloutput.txt"/>
         <outputImplementors implementer="cocomore" location="outputimplementors/cocomore/translate/html/translate6htmloutput.txt"/>
         <outputImplementors implementer="linguaserve" location="outputimplementors/linguaserve/translate/html/translate6htmloutput.txt"/>
      </inputfile>
      <inputfile location="inputdata/translate/xml/translate3xml.xml" conformance-class="xml-global">
         <description assertions="translate-global link-external-rules">Global - Embedded and linked rules</description>
         <expectedOutput location="expected/translate/xml/translate3xmloutput.txt"/>
         <outputImplementors implementer="enlaso" location="outputimplementors/enlaso/translate/xml/translate3xmloutput.txt"/>
         <outputImplementors implementer="ul" location="outputimplementors/ul/translate/xml/translate3xmloutput.txt"/>
         <outputImplementors implementer="shaun" location="outputimplementors/shaun/translate/xml/translate3xmloutput.txt"/>
         <outputImplementors implementer="dcu" location="outputimplementors/dcu/translate/xml/translate3xmloutput.txt"/>
         <outputImplementors implementer="linguaserve" location="outputimplementors/linguaserve/translate/xml/translate3xmloutput.txt"/>
         <outputImplementors implementer="adobe" location="outputimplementors/adobe/translate/xml/translate3xmloutput.txt"/>
      </inputfile>
      <inputfile location="inputdata/translate/xml/translate4xml.xml" conformance-class="xml-local">
         <description assertions="translate-local">Local - In host element</description>
         <expectedOutput location="expected/translate/xml/translate4xmloutput.txt"/>
         <outputImplementors implementer="enlaso" location="outputimplementors/enlaso/translate/xml/translate4xmloutput.txt"/>
         <outputImplementors implementer="ul" location="outputimplementors/ul/translate/xml/translate4xmloutput.txt"/>
         <outputImplementors implementer="shaun" location="outputimplementors/shaun/translate/xml/translate4xmloutput.txt"/>
         <outputImplementors implementer="dcu" location="outputimplementors/dcu/translate/xml/translate4xmloutput.txt"/>
         <outputImplementors implementer="linguaserve" location="outputimplementors/linguaserve/translate/xml/translate4xmloutput.txt"/>
      </inputfile>
      <inputfile location="inputdata/translate/html/translate2html.html" conformance-class="html-local">
         <description assertions="translate-local html5-markup">Local - In host element</description>
         <expectedOutput location="expected/translate/html/translate2htmloutput.txt"/>
         <outputImplementors implementer="enlaso" location="outputimplementors/enlaso/translate/html/translate2htmloutput.txt"/>
         <outputImplementors implementer="ul" location="outputimplementors/ul/translate/html/translate2htmloutput.txt"/>
         <outputImplementors implementer="shaun" location="outputimplementors/shaun/translate/html/translate2htmloutput.txt"/>
         <outputImplementors implementer="dcu" location="outputimplementors/dcu/translate/html/translate2htmloutput.txt"/>
         <outputImplementors implementer="cocomore" location="outputimplementors/cocomore/translate/html/translate2htmloutput.txt"/>
         <outputImplementors implementer="linguaserve" location="outputimplementors/linguaserve/translate/html/translate2htmloutput.txt"/>
         <outputImplementors implementer="lucysoftware" location="outputimplementors/lucysoftware/translate/html/translate2htmloutput.txt"/>
      </inputfile>
      <inputfile location="inputdata/translate/xml/translate5xml.xml" conformance-class="xml-local">
         <description assertions="translate-local">Local - In &lt;its:span&gt;</description>
         <expectedOutput location="expected/translate/xml/translate5xmloutput.txt"/>
         <outputImplementors implementer="enlaso" location="outputimplementors/enlaso/translate/xml/translate5xmloutput.txt"/>
         <outputImplementors implementer="ul" location="outputimplementors/ul/translate/xml/translate5xmloutput.txt"/>
         <outputImplementors implementer="shaun" location="outputimplementors/shaun/translate/xml/translate5xmloutput.txt"/>
         <outputImplementors implementer="dcu" location="outputimplementors/dcu/translate/xml/translate5xmloutput.txt"/>
         <outputImplementors implementer="linguaserve" location="outputimplementors/linguaserve/translate/xml/translate5xmloutput.txt"/>
         <outputImplementors implementer="adobe" location="outputimplementors/adobe/translate/xml/translate5xmloutput.txt"/>
      </inputfile>
      <inputfile location="inputdata/translate/xml/translate6xml.xml" conformance-class="xml-global">
         <description assertions="translate-global">Global (with //*) and local rules</description>
         <expectedOutput location="expected/translate/xml/translate6xmloutput.txt"/>
         <outputImplementors implementer="enlaso" location="outputimplementors/enlaso/translate/xml/translate6xmloutput.txt"/>
         <outputImplementors implementer="ul" location="outputimplementors/ul/translate/xml/translate6xmloutput.txt"/>
         <outputImplementors implementer="shaun" location="outputimplementors/shaun/translate/xml/translate6xmloutput.txt"/>
         <outputImplementors implementer="dcu" location="outputimplementors/dcu/translate/xml/translate6xmloutput.txt"/>
         <outputImplementors implementer="linguaserve" location="outputimplementors/linguaserve/translate/xml/translate6xmloutput.txt"/>
      </inputfile>
      <inputfile location="inputdata/translate/html/translate3html.html" conformance-class="html-global">
         <description assertions="translate-global html5-global-rules">Global (with //*) and local rules</description>
         <expectedOutput location="expected/translate/html/translate3htmloutput.txt"/>
         <outputImplementors implementer="enlaso" location="outputimplementors/enlaso/translate/html/translate3htmloutput.txt"/>
         <outputImplementors implementer="ul" location="outputimplementors/ul/translate/html/translate3htmloutput.txt"/>
         <outputImplementors implementer="shaun" location="outputimplementors/shaun/translate/html/translate3htmloutput.txt"/>
         <outputImplementors implementer="dcu" location="outputimplementors/dcu/translate/html/translate3htmloutput.txt"/>
         <outputImplementors implementer="cocomore" location="outputimplementors/cocomore/translate/html/translate3htmloutput.txt"/>
         <outputImplementors implementer="linguaserve" location="outputimplementors/linguaserve/translate/html/translate3htmloutput.txt"/>
         <outputImplementors implementer="lucysoftware" location="outputimplementors/lucysoftware/translate/html/translate3htmloutput.txt"/>
      </inputfile>
      <inputfile location="inputdata/translate/xml/translate7xml.xml" conformance-class="xml-global">
         <description assertions="translate-global">Global (with /doc) and local rules</description>
         <expectedOutput location="expected/translate/xml/translate7xmloutput.txt"/>
         <outputImplementors implementer="enlaso" location="outputimplementors/enlaso/translate/xml/translate7xmloutput.txt"/>
         <outputImplementors implementer="ul" location="outputimplementors/ul/translate/xml/translate7xmloutput.txt"/>
         <outputImplementors implementer="shaun" location="outputimplementors/shaun/translate/xml/translate7xmloutput.txt"/>
         <outputImplementors implementer="dcu" location="outputimplementors/dcu/translate/xml/translate7xmloutput.txt"/>
         <outputImplementors implementer="linguaserve" location="outputimplementors/linguaserve/translate/xml/translate7xmloutput.txt"/>
      </inputfile>
      <inputfile location="inputdata/translate/html/translate4html.html" conformance-class="html-global">
         <description assertions="translate-global html5-global-rules">Global (with /doc) and local rules</description>
         <expectedOutput location="expected/translate/html/translate4htmloutput.txt"/>
         <outputImplementors implementer="enlaso" location="outputimplementors/enlaso/translate/html/translate4htmloutput.txt"/>
         <outputImplementors implementer="ul" location="outputimplementors/ul/translate/html/translate4htmloutput.txt"/>
         <outputImplementors implementer="shaun" location="outputimplementors/shaun/translate/html/translate4htmloutput.txt"/>
         <outputImplementors implementer="dcu" location="outputimplementors/dcu/translate/html/translate4htmloutput.txt"/>
         <outputImplementors implementer="cocomore" location="outputimplementors/cocomore/translate/html/translate4htmloutput.txt"/>
         <outputImplementors implementer="linguaserve" location="outputimplementors/linguaserve/translate/html/translate4htmloutput.txt"/>
         <outputImplementors implementer="lucysoftware" location="outputimplementors/lucysoftware/translate/html/translate4htmloutput.txt"/>
      </inputfile>
      <inputfile location="inputdata/translate/xml/translate8xml.xml" conformance-class="xml-global">
         <description assertions="translate-global selection-precedence">Global and local rules (inheritance)</description>
         <expectedOutput location="expected/translate/xml/translate8xmloutput.txt"/>
         <outputImplementors implementer="enlaso" location="outputimplementors/enlaso/translate/xml/translate8xmloutput.txt"/>
         <outputImplementors implementer="ul" location="outputimplementors/ul/translate/xml/translate8xmloutput.txt"/>
         <outputImplementors implementer="shaun" location="outputimplementors/shaun/translate/xml/translate8xmloutput.txt"/>
         <outputImplementors implementer="dcu" location="outputimplementors/dcu/translate/xml/translate8xmloutput.txt"/>
         <outputImplementors implementer="linguaserve" location="outputimplementors/linguaserve/translate/xml/translate8xmloutput.txt"/>
         <outputImplementors implementer="adobe" location="outputimplementors/adobe/translate/xml/translate8xmloutput.txt"/>
      </inputfile>
      <inputfile location="inputdata/translate/html/translate5html.html" conformance-class="html-local">
         <description assertions="translate-global html5-global-rules html5-selection-precedence">Global and local rules (inheritance)</description>
         <expectedOutput location="expected/translate/html/translate5htmloutput.txt"/>
         <outputImplementors implementer="enlaso" location="outputimplementors/enlaso/translate/html/translate5htmloutput.txt"/>
         <outputImplementors implementer="ul" location="outputimplementors/ul/translate/html/translate5htmloutput.txt"/>
         <outputImplementors implementer="shaun" location="outputimplementors/shaun/translate/html/translate5htmloutput.txt"/>
         <outputImplementors implementer="dcu" location="outputimplementors/dcu/translate/html/translate5htmloutput.txt"/>
         <outputImplementors implementer="cocomore" location="outputimplementors/cocomore/translate/html/translate5htmloutput.txt"/>
         <outputImplementors implementer="linguaserve" location="outputimplementors/linguaserve/translate/html/translate5htmloutput.txt"/>
         <outputImplementors implementer="lucysoftware" location="outputimplementors/lucysoftware/translate/html/translate5htmloutput.txt"/>
      </inputfile>
   </dataCategory>

   <!--Localization Note-->
   <dataCategory identifier="localization-note" name="Localization Note">
      <inputfile location="inputdata/localizationnote/xml/locnote1xml.xml" conformance-class="xml-global">
         <description assertions="locnote-global">Global - Embedded rules with locNote</description>
         <expectedOutput location="expected/localizationnote/xml/locnote1xmloutput.txt"/>
         <outputImplementors implementer="enlaso" location="outputimplementors/enlaso/localizationnote/xml/locnote1xmloutput.txt"/>
         <outputImplementors implementer="ul" location="outputimplementors/ul/localizationnote/xml/locnote1xmloutput.txt"/>
         <outputImplementors implementer="shaun" location="outputimplementors/shaun/localizationnote/xml/locnote1xmloutput.txt"/>
         <outputImplementors implementer="linguaserve" location="outputimplementors/linguaserve/localizationnote/xml/locnote1xmloutput.txt"/>
         <outputImplementors implementer="adobe" location="outputimplementors/adobe/localizationnote/xml/locnote1xmloutput.txt"/>
      </inputfile>
      <inputfile location="inputdata/localizationnote/html/locnote1html.html" conformance-class="html-global">
         <description assertions="locnote-global html5-external-global-rules">Global - Linked rules with locNote</description>
         <expectedOutput location="expected/localizationnote/html/locnote1htmloutput.txt"/>
         <outputImplementors implementer="enlaso" location="outputimplementors/enlaso/localizationnote/html/locnote1htmloutput.txt"/>
         <outputImplementors implementer="ul" location="outputimplementors/ul/localizationnote/html/locnote1htmloutput.txt"/>
         <outputImplementors implementer="shaun" location="outputimplementors/shaun/localizationnote/html/locnote1htmloutput.txt"/>
         <outputImplementors implementer="cocomore" location="outputimplementors/cocomore/localizationnote/html/locnote1htmloutput.txt"/>
         <outputImplementors implementer="linguaserve" location="outputimplementors/linguaserve/localizationnote/html/locnote1htmloutput.txt"/>
      </inputfile>
      <inputfile location="inputdata/localizationnote/xml/locnote2xml.xml" conformance-class="xml-global">
         <description assertions="locnote-global">Global - Embedded rules with locNotePointer</description>
         <expectedOutput location="expected/localizationnote/xml/locnote2xmloutput.txt"/>
         <outputImplementors implementer="enlaso" location="outputimplementors/enlaso/localizationnote/xml/locnote2xmloutput.txt"/>
         <outputImplementors implementer="ul" location="outputimplementors/ul/localizationnote/xml/locnote2xmloutput.txt"/>
         <outputImplementors implementer="shaun" location="outputimplementors/shaun/localizationnote/xml/locnote2xmloutput.txt"/>
         <outputImplementors implementer="linguaserve" location="outputimplementors/linguaserve/localizationnote/xml/locnote2xmloutput.txt"/>
         <outputImplementors implementer="adobe" location="outputimplementors/adobe/localizationnote/xml/locnote2xmloutput.txt"/>
      </inputfile>
      <inputfile location="inputdata/localizationnote/html/locnote2html.html" conformance-class="html-global">
         <description assertions="locnote-global html5-external-global-rules">Global - Linked rules with locNotePointer</description>
         <expectedOutput location="expected/localizationnote/html/locnote2htmloutput.txt"/>
         <outputImplementors implementer="enlaso" location="outputimplementors/enlaso/localizationnote/html/locnote2htmloutput.txt"/>
         <outputImplementors implementer="ul" location="outputimplementors/ul/localizationnote/html/locnote2htmloutput.txt"/>
         <outputImplementors implementer="shaun" location="outputimplementors/shaun/localizationnote/html/locnote2htmloutput.txt"/>
         <outputImplementors implementer="cocomore" location="outputimplementors/cocomore/localizationnote/html/locnote2htmloutput.txt"/>
         <outputImplementors implementer="linguaserve" location="outputimplementors/linguaserve/localizationnote/html/locnote2htmloutput.txt"/>
      </inputfile>
      <inputfile location="inputdata/localizationnote/xml/locnote3xml.xml" conformance-class="xml-global">
         <description assertions="locnote-global">Global - Embedded rules with locNoteRef</description>
         <expectedOutput location="expected/localizationnote/xml/locnote3xmloutput.txt"/>
         <outputImplementors implementer="enlaso" location="outputimplementors/enlaso/localizationnote/xml/locnote3xmloutput.txt"/>
         <outputImplementors implementer="ul" location="outputimplementors/ul/localizationnote/xml/locnote3xmloutput.txt"/>
         <outputImplementors implementer="shaun" location="outputimplementors/shaun/localizationnote/xml/locnote3xmloutput.txt"/>
         <outputImplementors implementer="linguaserve" location="outputimplementors/linguaserve/localizationnote/xml/locnote3xmloutput.txt"/>
         <outputImplementors implementer="adobe" location="outputimplementors/adobe/localizationnote/xml/locnote3xmloutput.txt"/>
      </inputfile>
      <inputfile location="inputdata/localizationnote/html/locnote3html.html" conformance-class="html-global">
         <description assertions="locnote-global html5-external-global-rules">Global - Linked rules with locNoteRef</description>
         <expectedOutput location="expected/localizationnote/html/locnote3htmloutput.txt"/>
         <outputImplementors implementer="enlaso" location="outputimplementors/enlaso/localizationnote/html/locnote3htmloutput.txt"/>
         <outputImplementors implementer="ul" location="outputimplementors/ul/localizationnote/html/locnote3htmloutput.txt"/>
         <outputImplementors implementer="shaun" location="outputimplementors/shaun/localizationnote/html/locnote3htmloutput.txt"/>
         <outputImplementors implementer="cocomore" location="outputimplementors/cocomore/localizationnote/html/locnote3htmloutput.txt"/>
         <outputImplementors implementer="linguaserve" location="outputimplementors/linguaserve/localizationnote/html/locnote3htmloutput.txt"/>
      </inputfile>
      <inputfile location="inputdata/localizationnote/xml/locnote4xml.xml" conformance-class="xml-global">
         <description assertions="locnote-global">Global - Embedded rules with locNoteRefPointer</description>
         <expectedOutput location="expected/localizationnote/xml/locnote4xmloutput.txt"/>
         <outputImplementors implementer="enlaso" location="outputimplementors/enlaso/localizationnote/xml/locnote4xmloutput.txt"/>
         <outputImplementors implementer="ul" location="outputimplementors/ul/localizationnote/xml/locnote4xmloutput.txt"/>
         <outputImplementors implementer="shaun" location="outputimplementors/shaun/localizationnote/xml/locnote4xmloutput.txt"/>
         <outputImplementors implementer="linguaserve" location="outputimplementors/linguaserve/localizationnote/xml/locnote4xmloutput.txt"/>
         <outputImplementors implementer="adobe" location="outputimplementors/adobe/localizationnote/xml/locnote4xmloutput.txt"/>
      </inputfile>
      <inputfile location="inputdata/localizationnote/html/locnote4html.html" conformance-class="html-global">
         <description assertions="locnote-global html5-external-global-rules">Global - Linked rules with locNoteRefPointer</description>
         <expectedOutput location="expected/localizationnote/html/locnote4htmloutput.txt"/>
         <outputImplementors implementer="enlaso" location="outputimplementors/enlaso/localizationnote/html/locnote4htmloutput.txt"/>
         <outputImplementors implementer="ul" location="outputimplementors/ul/localizationnote/html/locnote4htmloutput.txt"/>
         <outputImplementors implementer="shaun" location="outputimplementors/shaun/localizationnote/html/locnote4htmloutput.txt"/>
         <outputImplementors implementer="cocomore" location="outputimplementors/cocomore/localizationnote/html/locnote4htmloutput.txt"/>
         <outputImplementors implementer="linguaserve" location="outputimplementors/linguaserve/localizationnote/html/locnote4htmloutput.txt"/>
      </inputfile>
      <inputfile location="inputdata/localizationnote/xml/locnote5xml.xml" conformance-class="xml-global">
         <description assertions="locnote-global link-external-rules">Global - Linked rules with locNote</description>
         <expectedOutput location="expected/localizationnote/xml/locnote5xmloutput.txt"/>
         <outputImplementors implementer="enlaso" location="outputimplementors/enlaso/localizationnote/xml/locnote5xmloutput.txt"/>
         <outputImplementors implementer="ul" location="outputimplementors/ul/localizationnote/xml/locnote5xmloutput.txt"/>
         <outputImplementors implementer="shaun" location="outputimplementors/shaun/localizationnote/xml/locnote5xmloutput.txt"/>
         <outputImplementors implementer="linguaserve" location="outputimplementors/linguaserve/localizationnote/xml/locnote5xmloutput.txt"/>
         <outputImplementors implementer="adobe" location="outputimplementors/adobe/localizationnote/xml/locnote5xmloutput.txt"/>
      </inputfile>
      <inputfile location="inputdata/localizationnote/html/locnote5html.html" conformance-class="html-global">
         <description assertions="locnote-global html5-external-global-rules">Global - Linked rules with locNote</description>
         <expectedOutput location="expected/localizationnote/html/locnote5htmloutput.txt"/>
         <outputImplementors implementer="enlaso" location="outputimplementors/enlaso/localizationnote/html/locnote5htmloutput.txt"/>
         <outputImplementors implementer="ul" location="outputimplementors/ul/localizationnote/html/locnote5htmloutput.txt"/>
         <outputImplementors implementer="shaun" location="outputimplementors/shaun/localizationnote/html/locnote5htmloutput.txt"/>
         <outputImplementors implementer="cocomore" location="outputimplementors/cocomore/localizationnote/html/locnote5htmloutput.txt"/>